// backend/src/models/Incident.js
// Enterprise-grade Incident Management Model with Timeline & Comments

import mongoose from 'mongoose';

const timelineEntrySchema = new mongoose.Schema({
  action: {
    type: String,
    required: true,
    enum: [
      'created',
      'assigned',
      'status_changed',
      'comment_added',
      'evidence_added',
      'severity_changed',
      'auto_generated'
    ]
  },
  message: {
    type: String,
    required: true
  },
  updated_by: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    default: null
  },
  timestamp: {
    type: Date,
    default: Date.now
  },
  metadata: {
    type: mongoose.Schema.Types.Mixed,
    default: {}
  }
}, { _id: true });

const commentSchema = new mongoose.Schema({
  user: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true
  },
  comment: {
    type: String,
    required: true,
    maxlength: 2000
  },
  timestamp: {
    type: Date,
    default: Date.now
  }
}, { _id: true });

const incidentSchema = new mongoose.Schema({
  // Human-friendly unique ID
  incident_id: {
    type: String,
    unique: true,
    required: false  // Auto-generated by pre-save hook
  },

  // Basic Information
  title: {
    type: String,
    required: true,
    trim: true,
    maxlength: 200
  },
  description: {
    type: String,
    trim: true,
    maxlength: 2000
  },

  // Related Data
  related_log_ids: [{
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Log'
  }],
  related_alert_ids: [{
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Alert'
  }],

  // Attack Classification
  attack_type: {
    type: String,
    enum: ['sql_injection', 'xss', 'brute_force', 'port_scan', 'data_exfiltration', 'ddos', 'malware', 'other'],
    default: 'other'
  },
  severity: {
    type: String,
    enum: ['low', 'medium', 'high', 'critical'],
    default: 'medium'
  },

  // Lifecycle Status
  status: {
    type: String,
    enum: ['open', 'in_progress', 'mitigated', 'resolved', 'closed'],
    default: 'open'
  },

  // Creation Type (auto-generated or manually escalated)
  creation_type: {
    type: String,
    enum: ['auto', 'manual'],
    default: 'manual',
    index: true
  },

  // Timestamps
  created_at: {
    type: Date,
    default: Date.now
  },
  updated_at: {
    type: Date,
    default: Date.now
  },

  // Assignment & Responsibility
  created_by: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    default: null
  },
  assigned_to: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    default: null
  },

  // Timeline - Forensic Audit Trail
  timeline: [timelineEntrySchema],

  // Comments - Discussion Thread
  comments: [commentSchema],

  // Metadata
  metadata: {
    src_ip: String,
    dest_system: String,
    geo: {
      country: String,
      city: String
    }
  }
}, {
  timestamps: { createdAt: 'created_at', updatedAt: 'updated_at' }
});

// Indexes for performance
incidentSchema.index({ incident_id: 1 }, { unique: true });
incidentSchema.index({ severity: 1, status: 1 });
incidentSchema.index({ created_at: -1 });
incidentSchema.index({ assigned_to: 1 });
incidentSchema.index({ status: 1 });

// Auto-generate incident ID before saving
incidentSchema.pre('save', async function (next) {
  if (this.isNew && !this.incident_id) {
    const year = new Date().getFullYear();
    const count = await mongoose.model('Incident').countDocuments();
    this.incident_id = `INC-${year}-${String(count + 1).padStart(5, '0')}`;
  }
  next();
});

const Incident = mongoose.model('Incident', incidentSchema);

export default Incident;
