// backend/src/controllers/incidentController.js
// Enterprise Incident Management Controller

import Incident from '../models/Incident.js';
import Alert from '../models/alert.model.js';
import Log from '../models/log.model.js';
import User from '../models/user.model.js';
import { generateRemediation, clearRemediationCache } from '../services/aiRemediationService.js';

/**
 * Helper: Add timeline entry
 */
const addTimelineEntry = (incident, action, message, userId, metadata = {}) => {
  incident.timeline.push({
    action,
    message,
    updated_by: userId || null,
    timestamp: new Date(),
    metadata
  });
};

/**
 * POST /api/incidents
 * Create a new incident (manual or automated)
 */
export const createIncident = async (req, res) => {
  try {
    const {
      title,
      description,
      related_log_ids = [],
      related_alert_ids = [],
      attack_type = 'other',
      severity = 'medium',
      metadata = {},
      auto_generated = false,
      creation_type = 'manual'
    } = req.body;

    if (!title) {
      return res.status(400).json({
        success: false,
        error: 'Title is required'
      });
    }

    // Create incident
    const incident = new Incident({
      title,
      description,
      related_log_ids,
      related_alert_ids,
      attack_type,
      severity,
      status: 'open',
      created_by: req.user?.id || null,
      creation_type,
      metadata
    });

    // Add creation timeline entry
    if (auto_generated) {
      addTimelineEntry(
        incident,
        'auto_generated',
        'Incident auto-generated by RuleEngine',
        null,
        { rule: 'automated_detection' }
      );
    } else {
      addTimelineEntry(
        incident,
        'created',
        `Incident created by ${req.user?.fullName || 'System'}`,
        req.user?.id
      );
    }

    await incident.save();

    // Link alerts to incident
    if (related_alert_ids.length > 0) {
      await Alert.updateMany(
        { _id: { $in: related_alert_ids } },
        { incident_id: incident._id }
      );
    }

    console.log(`📋 Incident created: ${incident.incident_id} - ${title}`);

    // Emit WebSocket event
    if (req.io) {
      req.io.emit('incident:new', {
        incident_id: incident.incident_id,
        title: incident.title,
        severity: incident.severity,
        timestamp: incident.created_at
      });
    }

    res.status(201).json({
      success: true,
      message: 'Incident created successfully',
      incident
    });
  } catch (error) {
    console.error('❌ Error creating incident:', error);
    res.status(500).json({
      success: false,
      error: 'Failed to create incident',
      message: error.message
    });
  }
};

/**
 * GET /api/incidents
 * Fetch incidents with filtering and role-based access
 */
export const getIncidents = async (req, res) => {
  try {
    const { severity, status, limit = 50, skip = 0, assigned_to } = req.query;
    const userRole = req.user?.role;
    const userId = req.user?.id;

    console.log('📋 Get Incidents - User:', req.user?.email, 'Role:', userRole, 'Permissions:', req.user?.permissions);

    let query = {};

    // Role-based filtering
    if (userRole === 'admin') {
      // Admin sees all incidents
      console.log('👑 Admin - showing all incidents');
    } else if (userRole === 'analyst') {
      // Analysts ALWAYS see incidents assigned to them OR created by them
      // Analysts with viewIncidents permission ALSO see all other incidents
      const hasViewPermission = req.user?.permissions?.viewIncidents;
      console.log('👤 Analyst - viewIncidents permission:', hasViewPermission);
      
      if (!hasViewPermission) {
        // Without permission: only assigned/created incidents
        query.$or = [
          { assigned_to: userId },
          { created_by: userId }
        ];
        console.log('🔒 Limited to assigned/created incidents only');
      } else {
        // With permission: see all incidents (assigned + all others)
        console.log('✅ Full access - showing all incidents (including assigned)');
      }
    } else {
      // Viewer sees limited info (handled in select)
      console.log('👁️ Viewer role');
    }

    // Additional filters
    if (severity) query.severity = severity;
    if (status) query.status = status;
    if (assigned_to) query.assigned_to = assigned_to;

    const [incidents, total] = await Promise.all([
      Incident.find(query)
        .sort({ created_at: -1 })
        .skip(parseInt(skip))
        .limit(parseInt(Math.min(limit, 500)))
        .populate('assigned_to', 'fullName email')
        .populate('created_by', 'fullName email')
        .populate({
          path: 'timeline.updated_by',
          select: 'fullName email'
        })
        .lean(),
      Incident.countDocuments(query)
    ]);

    console.log(`📊 Found ${incidents.length} incidents (total: ${total})`);

    res.json({
      success: true,
      count: incidents.length,
      total,
      skip: parseInt(skip),
      limit: parseInt(limit),
      incidents
    });
  } catch (error) {
    console.error('❌ Error fetching incidents:', error);
    res.status(500).json({
      success: false,
      error: 'Failed to fetch incidents',
      message: error.message
    });
  }
};

/**
 * GET /api/incidents/:id
 * Fetch incident with all related data
 */
export const getIncidentById = async (req, res) => {
  try {
    const { id } = req.params;
    const userRole = req.user?.role;
    const userId = req.user?.id;

    const incident = await Incident.findById(id)
      .populate('assigned_to', 'fullName email role')
      .populate('created_by', 'fullName email role')
      .populate({
        path: 'timeline.updated_by',
        select: 'fullName email'
      })
      .populate({
        path: 'comments.user',
        select: 'fullName email role'
      })
      .populate('related_alert_ids')
      .lean();

    if (!incident) {
      return res.status(404).json({
        success: false,
        error: 'Incident not found'
      });
    }

    // Check access permissions
    if (userRole === 'analyst') {
      const hasAccess = 
        incident.assigned_to?._id?.toString() === userId ||
        incident.created_by?._id?.toString() === userId;
      
      if (!hasAccess) {
        return res.status(403).json({
          success: false,
          error: 'Access denied. You can only view incidents assigned to you or created by you.'
        });
      }
    }

    // Fetch related logs
    const relatedLogs = await Log.find({
      _id: { $in: incident.related_log_ids }
    }).lean();

    res.json({
      success: true,
      incident: {
        ...incident,
        related_logs: relatedLogs
      }
    });
  } catch (error) {
    console.error('❌ Error fetching incident:', error);
    res.status(500).json({
      success: false,
      error: 'Failed to fetch incident',
      message: error.message
    });
  }
};

/**
 * PATCH /api/incidents/:id/status
 * Update incident status with workflow validation
 */
export const updateIncidentStatus = async (req, res) => {
  try {
    const { id } = req.params;
    const { status } = req.body;
    const userRole = req.user?.role;

    const validStatuses = ['open', 'in_progress', 'mitigated', 'resolved', 'closed'];
    if (!validStatuses.includes(status)) {
      return res.status(400).json({
        success: false,
        error: 'Invalid status'
      });
    }

    const incident = await Incident.findById(id);
    if (!incident) {
      return res.status(404).json({
        success: false,
        error: 'Incident not found'
      });
    }

    const oldStatus = incident.status;

    // Role-based workflow validation
    if (userRole === 'analyst') {
      // Analyst can only update their assigned incidents
      if (incident.assigned_to?.toString() !== req.user.id) {
        return res.status(403).json({
          success: false,
          error: 'You can only update incidents assigned to you'
        });
      }

      // Analyst workflow restrictions
      const allowedTransitions = {
        'open': ['in_progress'],
        'in_progress': ['mitigated'],
        'mitigated': ['resolved'],
        'resolved': []
      };

      if (!allowedTransitions[oldStatus]?.includes(status)) {
        return res.status(403).json({
          success: false,
          error: `Analysts cannot change status from ${oldStatus} to ${status}`
        });
      }
    }

    // Admin can change to any status including 'closed'
    if (status === 'closed' && userRole !== 'admin') {
      return res.status(403).json({
        success: false,
        error: 'Only admins can close incidents'
      });
    }

    // Update status
    incident.status = status;
    incident.updated_at = new Date();

    // Add timeline entry
    addTimelineEntry(
      incident,
      'status_changed',
      `Status changed from ${oldStatus.toUpperCase()} to ${status.toUpperCase()}`,
      req.user.id,
      { old_status: oldStatus, new_status: status }
    );

    await incident.save();

    // Emit WebSocket event
    if (req.io) {
      req.io.emit('incident:status_updated', {
        incident_id: incident.incident_id,
        status: incident.status,
        timestamp: incident.updated_at
      });
    }

    res.json({
      success: true,
      message: `Incident status updated to ${status}`,
      incident
    });
  } catch (error) {
    console.error('❌ Error updating incident status:', error);
    res.status(500).json({
      success: false,
      error: 'Failed to update incident status',
      message: error.message
    });
  }
};

/**
 * PATCH /api/incidents/:id/assign
 * Assign incident to analyst (admin only)
 */
export const assignIncident = async (req, res) => {
  try {
    const { id } = req.params;
    const { assigned_to } = req.body;

    if (!assigned_to) {
      return res.status(400).json({
        success: false,
        error: 'assigned_to user ID is required'
      });
    }

    // Verify assignee exists and is an analyst
    const assignee = await User.findById(assigned_to);
    if (!assignee) {
      return res.status(404).json({
        success: false,
        error: 'Assignee user not found'
      });
    }

    if (assignee.role !== 'analyst' && assignee.role !== 'admin') {
      return res.status(400).json({
        success: false,
        error: 'Can only assign to analysts or admins'
      });
    }

    const incident = await Incident.findById(id);
    if (!incident) {
      return res.status(404).json({
        success: false,
        error: 'Incident not found'
      });
    }

    incident.assigned_to = assigned_to;
    incident.updated_at = new Date();

    // Add timeline entry
    addTimelineEntry(
      incident,
      'assigned',
      `Incident assigned to ${assignee.fullName}`,
      req.user.id,
      { assigned_to_name: assignee.fullName, assigned_to_email: assignee.email }
    );

    await incident.save();
    await incident.populate('assigned_to', 'fullName email');

    // Emit WebSocket event
    if (req.io) {
      req.io.emit('incident:assigned', {
        incident_id: incident.incident_id,
        assigned_to: assignee.fullName,
        timestamp: incident.updated_at
      });
    }

    res.json({
      success: true,
      message: 'Incident assigned successfully',
      incident
    });
  } catch (error) {
    console.error('❌ Error assigning incident:', error);
    res.status(500).json({
      success: false,
      error: 'Failed to assign incident',
      message: error.message
    });
  }
};

/**
 * POST /api/incidents/:id/comment
 * Add comment to incident
 */
export const addComment = async (req, res) => {
  try {
    const { id } = req.params;
    const { comment } = req.body;

    if (!comment || comment.trim().length === 0) {
      return res.status(400).json({
        success: false,
        error: 'Comment is required'
      });
    }

    const incident = await Incident.findById(id);
    if (!incident) {
      return res.status(404).json({
        success: false,
        error: 'Incident not found'
      });
    }

    // Add comment
    incident.comments.push({
      user: req.user.id,
      comment: comment.trim(),
      timestamp: new Date()
    });

    // Add timeline entry
    addTimelineEntry(
      incident,
      'comment_added',
      `${req.user.fullName} added a comment`,
      req.user.id
    );

    incident.updated_at = new Date();
    await incident.save();

    // Populate user info for response
    await incident.populate({
      path: 'comments.user',
      select: 'fullName email role'
    });

    res.json({
      success: true,
      message: 'Comment added successfully',
      incident
    });
  } catch (error) {
    console.error('❌ Error adding comment:', error);
    res.status(500).json({
      success: false,
      error: 'Failed to add comment',
      message: error.message
    });
  }
};

/**
 * PATCH /api/incidents/:id/add-logs
 * Attach more logs to incident
 */
export const addLogs = async (req, res) => {
  try {
    const { id } = req.params;
    const { log_ids } = req.body;

    if (!Array.isArray(log_ids) || log_ids.length === 0) {
      return res.status(400).json({
        success: false,
        error: 'log_ids must be a non-empty array'
      });
    }

    const incident = await Incident.findById(id);
    if (!incident) {
      return res.status(404).json({
        success: false,
        error: 'Incident not found'
      });
    }

    // Add logs (avoid duplicates)
    const existingIds = incident.related_log_ids.map(id => id.toString());
    const newLogIds = log_ids.filter(logId => !existingIds.includes(logId.toString()));

    if (newLogIds.length > 0) {
      incident.related_log_ids.push(...newLogIds);

      // Add timeline entry
      addTimelineEntry(
        incident,
        'evidence_added',
        `${newLogIds.length} log(s) added as evidence`,
        req.user.id,
        { log_count: newLogIds.length }
      );

      incident.updated_at = new Date();
      await incident.save();
    }

    res.json({
      success: true,
      message: `${newLogIds.length} log(s) linked to incident`,
      incident
    });
  } catch (error) {
    console.error('❌ Error adding logs:', error);
    res.status(500).json({
      success: false,
      error: 'Failed to add logs',
      message: error.message
    });
  }
};

/**
 * GET /api/incidents/stats
 * Get incident statistics
 */
export const getIncidentStats = async (req, res) => {
  try {
    const now = new Date();
    const last7d = new Date(now - 7 * 24 * 60 * 60 * 1000);

    const [
      totalIncidents,
      openIncidents,
      criticalIncidents,
      severityStats,
      statusStats,
      recentIncidents
    ] = await Promise.all([
      Incident.countDocuments(),
      Incident.countDocuments({ status: 'open' }),
      Incident.countDocuments({ severity: 'critical', status: { $nin: ['resolved', 'closed'] } }),
      Incident.aggregate([
        { $group: { _id: '$severity', count: { $sum: 1 } } }
      ]),
      Incident.aggregate([
        { $group: { _id: '$status', count: { $sum: 1 } } }
      ]),
      Incident.find({ created_at: { $gte: last7d } }).countDocuments()
    ]);

    res.json({
      success: true,
      stats: {
        total_incidents: totalIncidents,
        open_incidents: openIncidents,
        critical_incidents: criticalIncidents,
        recent_incidents_7d: recentIncidents,
        severity_distribution: severityStats.reduce((acc, s) => {
          acc[s._id] = s.count;
          return acc;
        }, {}),
        status_distribution: statusStats.reduce((acc, s) => {
          acc[s._id] = s.count;
          return acc;
        }, {})
      }
    });
  } catch (error) {
    console.error('❌ Error fetching incident stats:', error);
    res.status(500).json({
      success: false,
      error: 'Failed to fetch statistics',
      message: error.message
    });
  }
};

/**
 * DELETE /api/incidents/:id
 * Delete incident (admin only)
 */
export const deleteIncident = async (req, res) => {
  try {
    const { id } = req.params;

    const incident = await Incident.findByIdAndDelete(id);

    if (!incident) {
      return res.status(404).json({
        success: false,
        error: 'Incident not found'
      });
    }

    res.json({
      success: true,
      message: 'Incident deleted successfully',
      incident_id: incident.incident_id
    });
  } catch (error) {
    console.error('❌ Error deleting incident:', error);
    res.status(500).json({
      success: false,
      error: 'Failed to delete incident',
      message: error.message
    });
  }
};

/**
 * GET /api/incidents/:id/remediation
 * Generate AI-powered remediation for incident
 * 
 * Flow:
 * 1. Fetch incident + related alerts
 * 2. Check if remediation exists in DB or cache
 * 3. If not, call AI service to generate
 * 4. Save to DB and return
 */
export const getIncidentRemediation = async (req, res) => {
  try {
    const { id } = req.params;
    const { regenerate = false } = req.query;

    // Fetch incident with related data
    const incident = await Incident.findById(id)
      .populate('related_alert_ids')
      .populate('created_by', 'fullName email')
      .populate('assigned_to', 'fullName email');

    if (!incident) {
      return res.status(404).json({
        success: false,
        error: 'Incident not found'
      });
    }

    console.log(`🤖 Remediation requested for ${incident.incident_id}`);

    // If regenerate flag is true, clear cache
    if (regenerate === 'true' || regenerate === true) {
      console.log('🔄 Regenerating remediation (cache cleared)');
      await clearRemediationCache(incident._id.toString());
      incident.remediation = null; // Clear DB copy
    }

    // Check if remediation already exists in DB
    if (incident.remediation && !regenerate) {
      console.log('✅ Returning existing remediation from DB');
      return res.json({
        success: true,
        remediation: incident.remediation,
        cached: true
      });
    }

    // Generate AI remediation
    const alerts = incident.related_alert_ids || [];
    const remediation = await generateRemediation(incident, alerts);

    // Save to incident document
    incident.remediation = remediation;
    await incident.save();

    console.log(`✅ Remediation saved for ${incident.incident_id}`);

    // Emit WebSocket event
    if (req.io) {
      req.io.emit('incident:remediation', {
        incident_id: incident.incident_id,
        timestamp: new Date()
      });
    }

    res.json({
      success: true,
      remediation,
      cached: false
    });

  } catch (error) {
    console.error('❌ Error generating remediation:', error);
    res.status(500).json({
      success: false,
      error: 'Failed to generate remediation',
      message: error.message
    });
  }
};

